theme: jekyll-theme-tactile

title: "Benjamin Merlin Bumpus"

description: "PhD student in Parameterized Complexity and Graph theory. 
              Schoool of Computing Science,
              University of Glasgow."
